version: '3'

services: 
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: backend
    volumes: 
      - .:/api
      - /api/node_modules
    ports: 
      - 3000:8080